ExemploCRUD/Controllers/SobreController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExemploCRUD.Models;

namespace ExemploCRUD.Controllers
{
    public class SobreController : Controller
    {
        private ContextoSobre db = new ContextoSobre();

        // GET: Sobre
        public ActionResult Index()
        {
            return View(db.Sobres.ToList());
        }

        // GET: Sobre/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sobre sobre = db.Sobres.Find(id);
            if (sobre == null)
            {
                return HttpNotFound();
            }
            return View(sobre);
        }

        // GET: Sobre/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sobre/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Codigo,Descricao")] Sobre sobre)
        {
            if (ModelState.IsValid)
            {
                db.Sobres.Add(sobre);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sobre);
        }

        // GET: Sobre/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sobre sobre = db.Sobres.Find(id);
            if (sobre == null)
            {
                return HttpNotFound();
            }
            return View(sobre);
        }

        // POST: Sobre/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Codigo,Descricao")] Sobre sobre)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sobre).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sobre);
        }

        // GET: Sobre/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sobre sobre = db.Sobres.Find(id);
            if (sobre == null)
            {
                return HttpNotFound();
            }
            return View(sobre);
        }

        // POST: Sobre/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sobre sobre = db.Sobres.Find(id);
            db.Sobres.Remove(sobre);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExemploCRUD/Views/Shared/_Layout.cshtml
<style type="text/css">
    .dropbtn {
        background-color: #4CAF50;
        color: white;
        padding: 16px;
        font-size: 16px;
        border: none;
        cursor: pointer;
    }
    .dropdown {
        position: relative;
        display: inline-block;
    }
    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f9f9f9;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
    }
    .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
    }
    .dropdown-content a:hover {
        background-color: #f1f1f1
    }
    .dropdown:hover .dropdown-content {
        display: block;
    }
    .dropdown:hover .dropbtn {
        background-color: #3e8e41;
    }
</style>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Games Sale - O maior leilão de jogos e acessórios</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: #ffd700; border-color: #ffd700">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href='@Url.Action("Index", "Home")'> <img width="300px" height="43px" src="/Content/Imagens/logo.png" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("SOBRE A GAMES SALE", "Sobre", "Home")</li>
                    <li>@Html.ActionLink("PATROCÍNIO", "Patrocinio", "Home")</li>
                    @{
                        if (Session["usuarioCodigo"] != null)
                        {
                            <li>
                                <div class="dropdown">
                                    <button class="dropbtn">LEILÕES</button>
                                    <div class="dropdown-content">
                                        @Html.ActionLink("Leilões", "IndexLeiloes", "Produto")
                                        @Html.ActionLink("Meus Leilões", "Index", "Produto")
                                        @Html.ActionLink("Leilões vencidos até o momento", "IndexLeiloesVencidos", "Produto")
                                    </div>
                                </div>
                            </li>
                        }
                        if (Session["usuarioCodigo"] != null && Session["usuarioTipo"].ToString()=="1")
                        {
                            <li style="padding-left: 5px;">
                                <div class="dropdown">
                                    <button class="dropbtn" style="background-color: #f00">ADMINISTRATIVO</button>
                                    <div class="dropdown-content">
                                        @Html.ActionLink("Usuários", "Index", "Usuario")
                                        @Html.ActionLink("Plataformas", "Index", "Plataforma")
                                        @Html.ActionLink("Categorias", "Index", "Categoria")
                                        @Html.ActionLink("Sobre", "Index", "Sobre")
                                    </div>
                                </div>
                            </li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

        <div style="clear: both;">
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Games Sale - Todos os direitos reservados</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>